server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: applog
    static_configs:
      - targets:
        - localhost
        labels:
          job: applog
          app: applog
          __path__: /app/logs/*.log

    pipeline_stages:
      - json:
          expressions:
            ip: ip
            method: method
            service: service
            msg: message
      - labels:
          ip:
          method:
          service:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: formatted
          template: >-
            {{- if .service }}
              {{.service | upper}}: {{.msg}}
            {{- else }}
              {{.method}} {{.ip}} "{{.user_agent}}" {{.path}}
            {{- end }}
