services:
  logstash:
    image: logstash:9.0.2
    environment:
      LS_JAVA_OPTS: '-Xms256m -Xmx256m'
    ports:
      - 5044:5044
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml

  elastic:
    image: elasticsearch:9.0.2
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      ES_JAVA_OPTS: '-Xmx1g -Xms1g'
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: true
      cluster.name: 'logging'
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}

  kibana:
    image: kibana:9.0.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${KIBANA_KEY}